import type { CampaignState } from "../types";

export const DEFAULT_STATE: CampaignState = {
  campaign: "My Campaign",
  currencies: [
    { id: "pp", name: "Platinum", symbol: "pp", rate: 10 },
    { id: "gp", name: "Gold", symbol: "gp", rate: 1 },
    { id: "ep", name: "Electrum", symbol: "ep", rate: 0.5 },
    { id: "sp", name: "Silver", symbol: "sp", rate: 0.1 },
    { id: "cp", name: "Copper", symbol: "cp", rate: 0.01 },
  ],
  transactions: [
    {
      id: "t1",
      date: "2026-04-01",
      description: "Starting funds",
      amounts: { gp: 50 },
      note: "Party treasury start",
    },
    {
      id: "t2",
      date: "2026-04-05",
      description: "Sold goblin loot",
      amounts: { gp: 12, sp: 5 },
      note: "",
    },
    {
      id: "t3",
      date: "2026-04-10",
      description: "Inn & supplies",
      amounts: { gp: -8, sp: -4 },
      note: "",
    },
  ],
  items: [
    {
      id: "i1",
      name: "Cloak of Elvenkind",
      description: "Grants advantage on Stealth checks.",
      carrier: "Aria",
      location: null,
      notable: true,
      qty: 1,
      tags: ["magic", "wondrous"],
      srd: true,
    },
    {
      id: "i2",
      name: "Bag of Holding",
      description: "Holds up to 500 lbs, 64 cubic feet.",
      carrier: null,
      location: "The Keep",
      notable: true,
      qty: 1,
      tags: ["magic", "wondrous"],
      srd: true,
    },
    {
      id: "i3",
      name: "Potion of Healing",
      description: "Restores 2d4+2 HP.",
      carrier: "Bronn",
      location: null,
      notable: false,
      qty: 3,
      tags: ["consumable", "potion"],
      srd: true,
    },
  ],
  locations: [
    "Party Inventory",
    "The Keep",
    "Ironforge Bank",
    "Millhaven Town",
  ],
  characters: ["Aria", "Bronn", "Cass", "Dex"],
};
